/**
 * Copyright Soramitsu Co., Ltd. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef KAGOME_EXCHANGE_MESSAGE_HPP
#define KAGOME_EXCHANGE_MESSAGE_HPP

#include "crypto/key.hpp"
#include "peer/peer_id.hpp"

namespace libp2p::security::plaintext {

  /**
   * Protobuf exchange message used by Plaintext 2.0 protocol
   * Structures generated by Google Protobuf are rather inconvenient, thus use
   * this one.
   * @see ExchangeMessageMarshaller
   */
  struct ExchangeMessage {
    crypto::PublicKey pubkey;
    peer::PeerId peer_id;
  };

}  // namespace libp2p::security::plaintext

#endif  // KAGOME_EXCHANGE_MESSAGE_HPP
