if(ASAN)
  print("Address Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_asan.cmake)
elseif(LSAN)
  print("Leak Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_lsan.cmake)
elseif(MSAN)
  print("Memory Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_msan.cmake)
elseif(TSAN)
  print("Thread Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_tsan.cmake)
elseif(UBSAN)
  print("Undefined Behavior Sanitizer is enabled")
  include(${CMAKE_CURRENT_LIST_DIR}/san/clang-8_cxx17_ubsan.cmake)
endif()
